# Generated by Django 6.0.2 on 2026-09-05 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('VERIFIED', 'Issue Verified'), ('ASSIGNED', 'Official Assigned'), ('IN_PROGRESS', 'Work In Progress'), ('RESOLVED', 'Issue Resolved'), ('CLOSED', 'Complaint Closed'), ('REOPENED', 'Complaint Reopened'), ('FEEDBACK_RECEIVED', 'Citizen Feedback Submitted'), ('DUPLICATE_FLAGGED', 'Possible Duplicate Flagged')], default='STATUS_CHANGE', max_length=40)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='complaints.complaint')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
