# Generated by Django 6.0.2 on 2026-09-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Prediction confidence from 0.0 to 1.0')),
                ('feature_summary', models.JSONField(blank=True, default=dict)),
                ('user_overridden', models.BooleanField(default=False, help_text='True if user or authority selected a different category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_distance_meters', models.FloatField(help_text='Haversine distance in meters')),
                ('text_similarity_score', models.FloatField(help_text='Text TF-IDF/Jaccard cosine similarity score (0.0 to 1.0)')),
                ('category_match', models.BooleanField(default=False)),
                ('image_similarity_score', models.FloatField(default=0.0, help_text='Visual perceptual/histogram similarity (0.0 to 1.0)')),
                ('combined_score', models.FloatField(help_text='Weighted composite similarity score (0.0 to 1.0)')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED_DUPLICATE', 'Confirmed Duplicate'), ('FALSE_POSITIVE', 'Distinct Issue')], default='PENDING', max_length=25)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-combined_score', '-flagged_at'],
            },
        ),
    ]
