# Generated by Django 6.0.2 on 2026-09-05 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('authentication', '0001_initial'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprediction',
            name='actual_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_by_user', to='complaints.category'),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='predicted_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_by_ai', to='complaints.category'),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='suggested_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department'),
        ),
        migrations.AddField(
            model_name='duplicatedetectionlog',
            name='matched_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_checks_as_existing', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='duplicatedetectionlog',
            name='new_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_checks_as_new', to='complaints.complaint'),
        ),
    ]
